configured_endpoints: 22
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/tzafon%2Fcomputer-02fec16933db8ec0ea8d32fefdd4199b27013df335839406baa685e6ffaac1f7.yml
openapi_spec_hash: c2c2af89ac127aecd7e0386c587bb9f2
config_hash: c1d4f9d7da2817f799deb3ccf0ce6f4b
